apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql-service
    app: basic-monitoring-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: mysql-pod
    app: basic-monitoring-app

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      name: mysql-pod
      app: basic-monitoring-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
        app: basic-monitoring-app
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # NEVER provide password in YML, Use secret
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "grafanadb"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
