apiVersion: v1

kind: Service

metadata:
  name: prometheus-internal-service
  labels:
    name: prometheus-internal-service
    app: basic-monitoring-app

spec:
  ports:
    - port: 9090
      targetPort: 9090

  selector:
    name: prometheus-pod
    app: basic-monitoring-app