apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-config-pv-volume
  labels:
    name: prometheus-config-pv
    app: basic-monitoring-app
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/prometheus/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-config-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
