apiVersion: v1

kind: Service

metadata:
  name: prometheus-service
  labels:
    name: prometheus-service
    app: basic-monitoring-app

spec:
  # type: LoadBalancer
  type: NodePort
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 30010
  selector:
    name: prometheus-pod
    app: basic-monitoring-app